<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>LogOutSimple</name>
  <uuid>4bb1dea0-a0e5-44b7-a7e5-12529d6b1226</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Hello World!"  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
